name: test
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^2.6.0


dependencies:
#   path: ^1.8.0
very_good_analysis: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
